export const dummyData = [
  {
    id: 1,
    writer: "abc",
    regData: "2025-04-25",
    title: "제목입니다1",
    content: "내용입니다1",
    likeCnt: 5,
    replyCnt: 5,
    readCnt: 20,
  },
  {
    id: 2,
    writer: "abc",
    regData: "2025-04-25",
    title: "제목입니다2",
    content: "내용입니다2",
    likeCnt: 5,
    replyCnt: 5,
    readCnt: 20,
  },
  {
    id: 3,
    writer: "abc",
    regData: "2025-04-25",
    title: "제목입니다3",
    content: "내용입니다3",
    likeCnt: 5,
    replyCnt: 5,
    readCnt: 20,
  },
  {
    id: 4,
    writer: "abc",
    regData: "2025-04-25",
    title: "제목입니다4",
    content: "내용입니다4",
    likeCnt: 5,
    replyCnt: 5,
    readCnt: 20,
  },
  {
    id: 5,
    writer: "abc",
    regData: "2025-04-25",
    title: "제목입니다5",
    content: "내용입니다5",
    likeCnt: 5,
    replyCnt: 5,
    readCnt: 20,
  },
];
